thsite/findways/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'findways'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^signin/$', views.signin, name = 'signin'),
    url(r'^signup/$', views.signup, name = 'signup'),
    url(r'^mytravel/$', views.mytravel, name='mytravel'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^logout/$', views.log_out, name ='logout')

]

thsite/thsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^findways/', include('findways.urls'))

]

thsite/findways/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE) #make a link between Auth model and Profile Model
    licence = models.BooleanField(default=False)
    card = models.BooleanField(default=False)
    navigo = models.BooleanField(default=False)
    velibPass = models.BooleanField(default=False)
    car = models.BooleanField(default=False)
    bike = models.BooleanField(default=False)


class Place(models.Model):
    name = models.CharField(max_length=50)
    lat = models.FloatField()
    long = models.FloatField()


# Enabling one to one link with the User authentification and the User Profile


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

thsite/findways/views.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound

from findways.backend.api_front import api
from .models import Profile


def index(request):
    return render(request,'findways/index.html')


def signup(request):
    error = False
    userAlreadyExists = False
    userIsCreated = False
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            userIsCreated = True
            user = User.objects.create_user(form.cleaned_data['username'], None, form.cleaned_data['password1'])
            user.save()
            return redirect('http://localhost:8000/findways/signin/')
    else:
        form = UserCreationForm()

    return render(request, 'findways/signup.html', locals())


def signin(request):
    error = False

    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
            else: # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()

    return render(request, 'findways/signin.html', locals())


@login_required(login_url='http://localhost:8000/findways/signin')
def mytravel(request):
    show_result = False
    try:
        if request.method == "POST":
            form = TravelForm(request.POST)
            if form.is_valid():
                show_result = True
                data = form.cleaned_data
                json1 = {'destination': data['destination'], 'car': request.user.profile.car, 'driving licence': request.user.profile.licence,
                        'navigo': request.user.profile.navigo, 'credit card': request.user.profile.card, 'velib': request.user.profile.velibPass,
                        'bike':request.user.profile.bike, 'criteria': int(data['criteria'])}
                json2 = api.ApiRoute(json1).data_structure()
                is_place = json1['criteria'] == 4
    except IndexError:
        return HttpResponse("Your address is not valid. Try again on the previous page.")
    except ValueError:
        return HttpResponse("Your address is not valid. Try again on the previous page.")
    else:
        form = TravelForm()

    return render(request, 'findways/mytravel.html', locals())


def log_out(request):
    logout(request)
    return redirect("http://localhost:8000/findways/")


def edit_profile(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect("http://localhost:8000/findways/mytravel")
    else :
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'findways/edit_profile.html', locals())


###################################################################################################################
# FORMS

class ConnexionForm(forms.Form):
    username = forms.CharField(label="Username ", max_length=30)
    password = forms.CharField(label="Password ", widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(label="Username ", max_length=30)
    mail = forms.CharField(label="E-mail ", max_length=50)
    password = forms.CharField(label="Password ", widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['licence', 'card', 'navigo', 'velibPass','car', 'bike']


class TravelForm(forms.Form):
    destination = forms.CharField(label = "Destination", max_length = 100)
    CHOICES = [(1, 'The fastest'), (2, 'The cheapest'), (3, 'The most convenient if I carry heavy loads'), (4, 'Visit the city !')]

    criteria = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

thsite/findways/templates/findways/edit_profile.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'findways/style.css' %}">
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/mytravel">
                <input type="button" class="btn btn-default button-main" value="Previous" />
            </a>
        </div>
        <div class="col-xs-offset-4 col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/logout">
                <input type="button" class="btn btn-default button-main pull-right" value="Log out" />
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 margin-top-10">
            <h1 class="title">Change my profile</h1>
        </div>
    </div>
    <div class="row">
        <form method="post" action="." class="margin-top-60">
            {% csrf_token %}
            <div class="col-xs-offset-5">
                {{ form.as_p }}
            </div>
            <input type="submit" class="btn btn-default button-main btn-lg col-xs-offset-3 col-xs-6 margin-top-60" value="Save" />
        </form>
    </div>
</div>

thsite/findways/templates/findways/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static from staticfiles %}
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'findways/style.css' %}">
        <title>TravelerHelper</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 margin-top-10">
                    <a href="http://localhost:8000/findways/logout">
                        <input type="button" class="btn btn-default button-main pull-right" value="Log out" />
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 margin-top-10">
                    <div class="jumbotron jumbotron-background">
                        <h1 class="center">Welcome to Traveler Helper</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 margin-top-30">
                    <a href="signin/">
                        <input type="button" class="btn btn-default button-main btn-lg btn-group col-xs-offset-3 col-xs-6" role="group" value="Log in" />
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 margin-top-60">
                    <a href="signup/">
                        <input type="button" class="btn btn-default button-main btn-lg col-xs-offset-3 col-xs-6" value="Sign in" />
                    </a>
                </div>
            </div>
        </div>
    </body>
</html>

thsite/findways/templates/findways/results.html
Tu veux vraiment voir tes résultats ? <br/>
{ json } <br/>
<a href="{% url 'findways:edit_profile' %}"><input type="button" value="Non" /></a>
<a href="http://localhost:8000/findways/logout"><input type="button" value="ou Non" /></a>

thsite/findways/templates/findways/signin.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'findways/style.css' %}">
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/">
                <input type="button" class="btn btn-default button-main" value="Previous" />
            </a>
        </div>
        <div class="col-xs-offset-4 col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/logout">
                <input type="button" class="btn btn-default button-main pull-right" value="Log out" />
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 margin-top-10">
            <h1 class="title">Log in</h1>
        </div>
    </div>
    <div class="row">
        {% if user.is_authenticated %}
            <span class="col-xs-12 margin-top-60 center blue">You are logged in, {{ user.username }} !</span>
            <a href="http://localhost:8000/findways/mytravel/">
                <input type="button" class="btn btn-default button-main btn-lg col-xs-offset-3 col-xs-6 margin-top-60" value="My way" />
            </a>
        {% else %}
            <form method="post" action="." class="margin-top-60">
                {% csrf_token %}
                <div class="col-xs-offset-4">
                    {{ form.as_p }}
                </div>
                <input type="submit" class="btn btn-default button-main btn-lg col-xs-offset-3 col-xs-6 margin-top-60" value="Log in" />
            </form>
        {% endif %}
    </div>
    <div class="row">
        {% if error %}
            <p class="warning-text"><strong>Unknown user or invalid password.</strong></p>
        {% endif %}
    </div>
</div>

thsite/findways/templates/findways/signup.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'findways/style.css' %}">
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/">
                <input type="button" class="btn btn-default button-main" value="Previous" />
            </a>
        </div>
        <div class="col-xs-offset-4 col-xs-4 margin-top-10">
            <a href="http://localhost:8000/findways/logout">
                <input type="button" class="btn btn-default button-main pull-right" value="Log out" />
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 margin-top-10">
            <h1 class="title">Sign in</h1>
        </div>
    </div>
    <div class="row">
        {% if error %}
            <p><strong>Unknown user or invalid password.</strong></p>
        {% elif userAlreadyExists %}
            <p><strong>Mmmmh, this user already exists...</strong></p>
        {% else %}
        <form method="post" action="." class="margin-top-60">
            {% csrf_token %}
            <div class="col-xs-offset-4">
                {{ form.as_p }}
            </div>
            <input type="submit" class="btn btn-default button-main btn-lg col-xs-offset-3 col-xs-6 margin-top-60" value="Sign in" />
        </form>
        {% endif %}
    </div>
</div>